# src/Ens/JulesBundle/Resources/config/routing.yml
EnsJulesBundle_job:
    resource: "@EnsJulesBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsJulesBundle_homepage:
    pattern:  /
    defaults: { _controller: EnsJulesBundle:Job:index }